// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiTutorial250818.WebApi.Data;

#nullable disable

namespace WebApiTutorial250818.WebApi.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20250826123048_teacherAndDepartment")]
    partial class teacherAndDepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiTutorial250818.WebApi.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credits = 7,
                            Title = "Introduction to Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Credits = 6,
                            Title = "Algorithms and Data Structures"
                        },
                        new
                        {
                            Id = 3,
                            Credits = 5,
                            Title = "Database Systems"
                        });
                });

            modelBuilder.Entity("WebApiTutorial250818.WebApi.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Department of Computer Science",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Department of Mathematics",
                            Name = "Mathematics"
                        });
                });

            modelBuilder.Entity("WebApiTutorial250818.WebApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonalEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1815, 12, 10),
                            FirstName = "Ada",
                            LastName = "Lovelace",
                            PersonalEmail = "ada.lovelace@example.com"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1912, 6, 23),
                            FirstName = "Alan",
                            LastName = "Turing",
                            PersonalEmail = "alan.turing@example.com"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(1906, 12, 9),
                            FirstName = "Grace",
                            LastName = "Hopper",
                            PersonalEmail = "grace.hopper@example.com"
                        });
                });

            modelBuilder.Entity("WebApiTutorial250818.WebApi.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonalEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1938, 1, 10),
                            FirstName = "Donald",
                            LastName = "Knuth",
                            PersonalEmail = "donald.knuth@example.com"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1939, 11, 7),
                            FirstName = "Barbara",
                            LastName = "Liskov",
                            PersonalEmail = "barbara.liskov@example.com"
                        });
                });

            modelBuilder.Entity("WebApiTutorial250818.WebApi.Models.TeacherDepartment", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("TeacherDepartments");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            DepartmentId = 1
                        },
                        new
                        {
                            TeacherId = 2,
                            DepartmentId = 1
                        },
                        new
                        {
                            TeacherId = 2,
                            DepartmentId = 2
                        });
                });

            modelBuilder.Entity("WebApiTutorial250818.WebApi.Models.TeacherDepartment", b =>
                {
                    b.HasOne("WebApiTutorial250818.WebApi.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiTutorial250818.WebApi.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
