// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiTutorial250818.WebApi.Data;

#nullable disable

namespace WebApiTutorial250818.WebApi.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20250814093741_course-added")]
    partial class courseadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiTutorial250818.WebApi.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credits = 7,
                            Title = "Introduction to Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Credits = 6,
                            Title = "Algorithms and Data Structures"
                        },
                        new
                        {
                            Id = 3,
                            Credits = 5,
                            Title = "Database Systems"
                        });
                });

            modelBuilder.Entity("WebApiTutorial250818.WebApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1815, 12, 10),
                            Email = "ada.lovelace@example.com",
                            FirstName = "Ada",
                            LastName = "Lovelace"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1912, 6, 23),
                            Email = "alan.turing@example.com",
                            FirstName = "Alan",
                            LastName = "Turing"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(1906, 12, 9),
                            Email = "grace.hopper@example.com",
                            FirstName = "Grace",
                            LastName = "Hopper"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
