// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiTutorial250818.WebApi.Data;

#nullable disable

namespace WebApiTutorial250818.WebApi.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiTutorial250818.WebApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1815, 12, 10),
                            Email = "ada.lovelace@example.com",
                            FirstName = "Ada",
                            LastName = "Lovelace"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1912, 6, 23),
                            Email = "alan.turing@example.com",
                            FirstName = "Alan",
                            LastName = "Turing"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(1906, 12, 9),
                            Email = "grace.hopper@example.com",
                            FirstName = "Grace",
                            LastName = "Hopper"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
